apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k0ute6ury-go 
  janus-idp.io/tekton: k0ute6ury-go
  backstage.io/kubernetes-id: k0ute6ury-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k0ute6ury-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml